import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    "asset-pipeline",
    {
      type: "category",
      label: "Asset Forge Dev Book",
      link: { type: "doc", id: "asset-forge/README" },
      items: [{ type: "autogenerated", dirName: "asset-forge" }],
    },
  ],
};

export default sidebars;
