#!/usr/bin/env bash

# Variable names only. Real values belong in local untracked runtime secret
# files such as /tmp/hyperscape-secrets.env or .env.production.

HYPERSCAPES_PERSONAL_RUNTIME_SECRET_REQUIRED_KEYS=(
  DATABASE_URL
  JWT_SECRET
  STREAMING_AUTOMATION_TOKEN
)

HYPERSCAPES_PERSONAL_RUNTIME_SECRET_OPTIONAL_KEYS=(
  BETTING_FEED_ACCESS_TOKEN
  STREAMING_VIEWER_ACCESS_TOKEN
  STREAM_INGEST_STREAM_KEY
  STREAM_INGEST_SRT_PASSPHRASE
)

HYPERSCAPES_PERSONAL_RUNTIME_RESERVED_CLOUDFLARE_KEYS=(
  STREAM_CLOUDFLARE_LIVE_INPUT_ID
  STREAM_CLOUDFLARE_WEBHOOK_SECRET
  STREAM_CLOUDFLARE_ACCOUNT_ID
)
