// Export classes with original names
export { Node } from './Node'
export { Group } from './Group'
export { Mesh } from './Mesh'
export { SkinnedMesh } from './SkinnedMesh'
export { LOD } from './LOD'
export { Audio } from './Audio'
export { Image } from './Image'
export { Avatar } from './Avatar'
export { Action } from './Action'
export { Anchor } from './Anchor'
export { Nametag } from './Nametag'
export { Particles } from './Particles'
export { Sky } from './Sky'
export { UI } from './UI'
export { UIView } from './UIView'
export { UIText } from './UIText'
export { UIImage } from './UIImage'
export { Controller } from './Controller'
export { RigidBody } from './RigidBody'
export { Collider } from './Collider'
export { Joint } from './Joint'

// Also export lowercase aliases for backwards compatibility
export { Group as group } from './Group'
export { Mesh as mesh } from './Mesh'
export { SkinnedMesh as skinnedmesh } from './SkinnedMesh'
export { LOD as lod } from './LOD'
export { Audio as audio } from './Audio'
export { Image as image } from './Image'
export { Avatar as avatar } from './Avatar'
export { Action as action } from './Action'
export { Anchor as anchor } from './Anchor'
export { Nametag as nametag } from './Nametag'
export { Particles as particles } from './Particles'
export { Sky as sky } from './Sky'
export { UI as ui } from './UI'
export { UIView as uiview } from './UIView'
export { UIText as uitext } from './UIText'
export { UIImage as uiimage } from './UIImage'
export { Controller as controller } from './Controller'
export { RigidBody as rigidbody } from './RigidBody'
export { Collider as collider } from './Collider'
export { Joint as joint } from './Joint'
