[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install -g bun', 'bun install']

[phases.build]
cmds = [
  'node server/scripts/migrate-manifests-to-postgres.mjs || true'
]

[start]
cmd = 'bun run start'

