[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm install -g bun', 'cd apps/api && bun install']

[phases.build]
cmds = [
  'cd apps/api && node server/scripts/migrate-manifests-to-postgres.mjs || true'
]

[start]
cmd = 'cd apps/api && bun run start'

