[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fight_oracle = "A6utqr1N4KP3Tst2tMCqfJR4mhCRNw4M2uN3Nb6nPBcS"
gold_clob_market = "4phSkAVkbtGbQbrT3p2xjNPLAyw1DWz99wT7g4dQMyiX"
gold_perps_market = "3WKQf3J4B8QqRyWcBLR7xrb9VFPVjkZwzyZS67AahDbK"

[programs.localnet]
fight_oracle = "A6utqr1N4KP3Tst2tMCqfJR4mhCRNw4M2uN3Nb6nPBcS"
gold_clob_market = "4phSkAVkbtGbQbrT3p2xjNPLAyw1DWz99wT7g4dQMyiX"
gold_perps_market = "3WKQf3J4B8QqRyWcBLR7xrb9VFPVjkZwzyZS67AahDbK"

[programs.mainnet]
fight_oracle = "4fvVdiZkMQQGjYWHyKubjkdhh1DfJaYNvaRvRWPeKcMN"
gold_clob_market = "AqRu5b1fd67VyR4MgjKPN9EMgQ8wxauDUxyY5pUsGdAW"
gold_perps_market = "3WKQf3J4B8QqRyWcBLR7xrb9VFPVjkZwzyZS67AahDbK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]
types = "../app/src/idl"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
